name: Build HTTrack AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create AppImageBuilder recipe
      run: |
        cat << EOF > AppImageBuilder.yml
        version: 1
        AppDir:
          path: ./AppDir
          app_info:
            id: com.httrack.webhttrack
            name: HTTrack
            icon: webhttrack
            version: "3.49.2"
            exec: usr/bin/webhttrack
          apt:
            arch: amd64
            sources:
              - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main universe'
            include:
              - webhttrack
              - libssl1.1
              - libqt5core5a
              - libqt5gui5
              - libqt5widgets5
          files:
            - usr/share/applications/webhttrack.desktop
            - usr/share/icons/hicolor/256x256/apps/webhttrack.png
        AppImage:
          arch: x86_64
          update-information: gh-releases-zsync|${GITHUB_REPOSITORY}|latest|HTTrack-*.AppImage.zsync
        EOF

    - name: Build AppImage
      uses: AppImageCrafters/build-appimage@master
      with:
        recipe: AppImageBuilder.yml
      env:
        UPDATE_INFO: gh-releases-zsync|${GITHUB_REPOSITORY}|latest|HTTrack-*.AppImage.zsync

    - name: Upload AppImage
      uses: actions/upload-artifact@v2
      with:
        name: HTTrack.AppImage
        path: HTTrack-*.AppImage
